# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'milvus_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14milvus_service.proto\x12\x0emilvus_service\"d\n\rSearchRequest\x12\x17\n\x0f\x63ollection_name\x18\x01 \x01(\t\x12\x14\n\x0cquery_vector\x18\x02 \x03(\x02\x12\r\n\x05limit\x18\x03 \x01(\x05\x12\x15\n\routput_fields\x18\x04 \x03(\t\"?\n\x0eSearchResponse\x12-\n\x07results\x18\x01 \x03(\x0b\x32\x1c.milvus_service.SearchResult\"\x95\x01\n\x0cSearchResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\x12\x38\n\x06\x65ntity\x18\x03 \x03(\x0b\x32(.milvus_service.SearchResult.EntityEntry\x1a-\n\x0b\x45ntityEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x14\n\x12HealthCheckRequest\"&\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\"\x18\n\x16ListCollectionsRequest\".\n\x17ListCollectionsResponse\x12\x13\n\x0b\x63ollections\x18\x01 \x03(\t\"/\n\x14HasCollectionRequest\x12\x17\n\x0f\x63ollection_name\x18\x01 \x01(\t\"\'\n\x15HasCollectionResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32\xf2\x02\n\rMilvusService\x12G\n\x06Search\x12\x1d.milvus_service.SearchRequest\x1a\x1e.milvus_service.SearchResponse\x12V\n\x0bHealthCheck\x12\".milvus_service.HealthCheckRequest\x1a#.milvus_service.HealthCheckResponse\x12\x62\n\x0fListCollections\x12&.milvus_service.ListCollectionsRequest\x1a\'.milvus_service.ListCollectionsResponse\x12\\\n\rHasCollection\x12$.milvus_service.HasCollectionRequest\x1a%.milvus_service.HasCollectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wiki_retriever.milvus_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHRESULT_ENTITYENTRY']._loaded_options = None
  _globals['_SEARCHRESULT_ENTITYENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHREQUEST']._serialized_start=40
  _globals['_SEARCHREQUEST']._serialized_end=140
  _globals['_SEARCHRESPONSE']._serialized_start=142
  _globals['_SEARCHRESPONSE']._serialized_end=205
  _globals['_SEARCHRESULT']._serialized_start=208
  _globals['_SEARCHRESULT']._serialized_end=357
  _globals['_SEARCHRESULT_ENTITYENTRY']._serialized_start=312
  _globals['_SEARCHRESULT_ENTITYENTRY']._serialized_end=357
  _globals['_HEALTHCHECKREQUEST']._serialized_start=359
  _globals['_HEALTHCHECKREQUEST']._serialized_end=379
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=381
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=419
  _globals['_LISTCOLLECTIONSREQUEST']._serialized_start=421
  _globals['_LISTCOLLECTIONSREQUEST']._serialized_end=445
  _globals['_LISTCOLLECTIONSRESPONSE']._serialized_start=447
  _globals['_LISTCOLLECTIONSRESPONSE']._serialized_end=493
  _globals['_HASCOLLECTIONREQUEST']._serialized_start=495
  _globals['_HASCOLLECTIONREQUEST']._serialized_end=542
  _globals['_HASCOLLECTIONRESPONSE']._serialized_start=544
  _globals['_HASCOLLECTIONRESPONSE']._serialized_end=583
  _globals['_MILVUSSERVICE']._serialized_start=586
  _globals['_MILVUSSERVICE']._serialized_end=956
# @@protoc_insertion_point(module_scope)
