# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import milvus_service_pb2 as milvus__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in milvus_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MilvusServiceStub(object):
    """Service definition for Milvus operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/milvus_service.MilvusService/Search',
                request_serializer=milvus__service__pb2.SearchRequest.SerializeToString,
                response_deserializer=milvus__service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/milvus_service.MilvusService/HealthCheck',
                request_serializer=milvus__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=milvus__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/milvus_service.MilvusService/ListCollections',
                request_serializer=milvus__service__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=milvus__service__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)
        self.HasCollection = channel.unary_unary(
                '/milvus_service.MilvusService/HasCollection',
                request_serializer=milvus__service__pb2.HasCollectionRequest.SerializeToString,
                response_deserializer=milvus__service__pb2.HasCollectionResponse.FromString,
                _registered_method=True)


class MilvusServiceServicer(object):
    """Service definition for Milvus operations
    """

    def Search(self, request, context):
        """Search for vectors in a collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """List collections
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HasCollection(self, request, context):
        """Check if collection exists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MilvusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=milvus__service__pb2.SearchRequest.FromString,
                    response_serializer=milvus__service__pb2.SearchResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=milvus__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=milvus__service__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=milvus__service__pb2.ListCollectionsRequest.FromString,
                    response_serializer=milvus__service__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'HasCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.HasCollection,
                    request_deserializer=milvus__service__pb2.HasCollectionRequest.FromString,
                    response_serializer=milvus__service__pb2.HasCollectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'milvus_service.MilvusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('milvus_service.MilvusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MilvusService(object):
    """Service definition for Milvus operations
    """

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/milvus_service.MilvusService/Search',
            milvus__service__pb2.SearchRequest.SerializeToString,
            milvus__service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/milvus_service.MilvusService/HealthCheck',
            milvus__service__pb2.HealthCheckRequest.SerializeToString,
            milvus__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/milvus_service.MilvusService/ListCollections',
            milvus__service__pb2.ListCollectionsRequest.SerializeToString,
            milvus__service__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HasCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/milvus_service.MilvusService/HasCollection',
            milvus__service__pb2.HasCollectionRequest.SerializeToString,
            milvus__service__pb2.HasCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
